from custom.amway.amway_config import AMWAY_SPEECH_DRAFT_CHOOSE_LLM, AMWAY_SPEECH_RESULT_CHOOSE_LLM
# 演讲稿草案生成所选模型类别
SPEECH_DRAFT_CHOOSE_LLM = "OpenAI" or AMWAY_SPEECH_DRAFT_CHOOSE_LLM
# 演讲稿终稿生成所选模型类别
SPEECH_RESULT_CHOOSE_LLM = "OpenAI" or AMWAY_SPEECH_RESULT_CHOOSE_LLM
