import os
TEST_PGVECTOR_DRIVER = "psycopg2"
TEST_PGVECTOR_HOST = os.environ.get("PGVECTOR_HOST") or "10.108.1.150"
TEST_PGVECTOR_PORT = "5432"
TEST_PGVECTOR_DATABASE = "chat_omni_pro"
TEST_PGVECTOR_USER = "chat_omni_pro"
TEST_PGVECTOR_PASSWORD = "E9YtVZ0TEISC"
TEST_PGVECTOR_DIMENSIONS = "1536"
