import os
TEST_REDIS_HOST = os.environ.get("REDIS_HOST") or "10.108.1.150"
TEST_REDIS_PORT = "6379"
TEST_REDIS_DATABASE = "2"
TEST_REDIS_PASSWD = "4bespin%E9q"
TEST_REDIS_MIN = "1"
TEST_REDIS_MAX = "20"
