TEST_HTTP_HOST = "http://47.236.254.2"

# 意图识别模型
TEST_INTENTION_RECOGNITION_MODEL = "DashScope"
TEST_INTENTION_RECOGNITION_MODEL_NAME = "qwen3-30b-a3b"
# 问题优化模型
TEST_QUES_OPTIMIZER_MODEL = "DashScope"
TEST_QUES_OPTIMIZER_MODEL_NAME = "qwen3-30b-a3b"
# 文件summary模型
TEST_FILES_SUMMARY_MODEL = "DashScope"
TEST_FILES_SUMMARY_MODEL_NAME = "qwen3-30b-a3b"
# 深度思考模型
TEST_THINKING_MODEL = "DashScope"
TEST_THINKING_MODEL_NAME = "qwen3-32b"
