from custom.amway.amway_config import AMWAY_SFT_SPEECH_ABSTRACT_CHOOSE_LLM, AMWAY_SFT_SPEECH_OUTLINES_CHOOSE_LLM, \
    AMWAY_SFT_SPEECH_PARAGRAPH_CHOOSE_LLM

# SFT数据-演讲稿摘要生成-所选模型类别
SFT_SPEECH_ABSTRACT_CHOOSE_LLM = "OpenAI" or AMWAY_SFT_SPEECH_ABSTRACT_CHOOSE_LLM
# SFT数据-演讲稿大纲生成-所选模型类别
SFT_SPEECH_OUTLINES_CHOOSE_LLM = "OpenAI" or AMWAY_SFT_SPEECH_OUTLINES_CHOOSE_LLM
# SFT数据-演讲稿段落生成-所选模型类别
SFT_SPEECH_PARAGRAPH_CHOOSE_LLM = "OpenAI" or AMWAY_SFT_SPEECH_PARAGRAPH_CHOOSE_LLM
