from config.base_config import APPLICATION_ENV_IS_TEST
from config.base_config_model_type import MODEL_TYPE_TEXT
from config.prod.prod_config_dashscope import PROD_BASHSCOPE_BASE_URL, PROD_BASHSCOPE_API_KEY, PROD_BASHSCOPE_VL_URL, \
    PROD_BASHSCOPE_THINKING_URL
from config.test.test_config_dashscope import TEST_BASHSCOPE_BASE_URL, TEST_BASHSCOPE_API_KEY, TEST_BASHSCOPE_VL_URL, \
    TEST_BASHSCOPE_THINKING_URL

BASHSCOPE_MODEL_NAME = "qwen3-30b-a3b"
BASHSCOPE_MODEL_TYPE = MODEL_TYPE_TEXT
BASHSCOPE_TOP_P = 0.9
BASHSCOPE_TOP_K = 999
BASHSCOPE_TEMPERATURE = 0.85
BASHSCOPE_BASE_URL = TEST_BASHSCOPE_BASE_URL if APPLICATION_ENV_IS_TEST else PROD_BASHSCOPE_BASE_URL
BASHSCOPE_THINKING_URL = TEST_BASHSCOPE_THINKING_URL if APPLICATION_ENV_IS_TEST else PROD_BASHSCOPE_THINKING_URL
BASHSCOPE_VL_URL = TEST_BASHSCOPE_VL_URL if APPLICATION_ENV_IS_TEST else PROD_BASHSCOPE_VL_URL
BASHSCOPE_HTTP_URL = "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
BASHSCOPE_MULTIMODAL_HTTP_URL = "https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation"
BASHSCOPE_API_KEY = TEST_BASHSCOPE_API_KEY if APPLICATION_ENV_IS_TEST else PROD_BASHSCOPE_API_KEY
BASHSCOPE_WANT_RESEND = False
BASHSCOPE_SEND_MIN = 1
BASHSCOPE_SEND_MAX = 999999999
BASHSCOPE_SECURE_ANSWER = "用户输入存在安全风险，建议关闭当前会话，清理历史会话信息。"
BASHSCOPE_MAX_TOKENS = 8192
