from config.base_config import APPLICATION_ENV_IS_TEST
from config.prod.prod_config_deepseek import PROD_DEEPSEEK_API_KEY_POOL, PROD_DEEPSEEK_URL
from config.test.test_config_deepseek import TEST_DEEPSEEK_API_KEY_POOL, TEST_DEEPSEEK_URL

DEEPSEEK_API_KEY_POOL = TEST_DEEPSEEK_API_KEY_POOL if APPLICATION_ENV_IS_TEST else PROD_DEEPSEEK_API_KEY_POOL
DEEPSEEK_URL = TEST_DEEPSEEK_URL if APPLICATION_ENV_IS_TEST else PROD_DEEPSEEK_URL
DEEPSEEK_MODEL_NAME = "deepseek-chat"
DEEPSEEK_MAX_TOKENS = 8192
DEEPSEEK_TEMPERATURE = 0.8
