import os
from config.base_config_openai import *
from config.base_config_vector import *
from config.prod.prod_base_config import PROD_HTTP_HOST, PROD_INTENTION_RECOGNITION_MODEL, \
    PROD_INTENTION_RECOGNITION_MODEL_NAME, PROD_THINKING_MODEL_NAME, PROD_QUES_OPTIMIZER_MODEL, \
    PROD_QUES_OPTIMIZER_MODEL_NAME, PROD_FILES_SUMMARY_MODEL, PROD_FILES_SUMMARY_MODEL_NAME, PROD_THINKING_MODEL
from config.test.test_base_config import TEST_HTTP_HOST, TEST_INTENTION_RECOGNITION_MODEL, \
    TEST_INTENTION_RECOGNITION_MODEL_NAME, TEST_QUES_OPTIMIZER_MODEL, TEST_QUES_OPTIMIZER_MODEL_NAME, \
    TEST_FILES_SUMMARY_MODEL, TEST_FILES_SUMMARY_MODEL_NAME, TEST_THINKING_MODEL, TEST_THINKING_MODEL_NAME
from config.test.test_config_mysql import *
from config.test.test_config_postgres import *
from config.test.test_config_redis import *
from config.prod.prod_config_mysql import *
from config.prod.prod_config_postgres import *
from config.prod.prod_config_redis import *

# 环境标识符
ENV_TEST = "test"
APPLICATION_ENV = os.environ.get("APPLICATION_ENV") or ENV_TEST
APPLICATION_ENV_IS_TEST = (APPLICATION_ENV == ENV_TEST)
# 底座大模型
DEFAULT_LLM = os.environ.get("DEFAULT_LLM") or "OpenAI"
CURRENT_LLM = "DashScope" or DEFAULT_LLM
# OpenAI配置
OPENAI_API_KEY = BASE_OPENAI_API_KEY or os.environ.get("OPENAI_API_KEY")
OPENAI_TEMPERATURE = BASE_OPENAI_TEMPERATURE or os.environ.get("OPENAI_TEMPERATURE")
OPENAI_OUTPUT_TOKEN_LENGTH = BASE_OPENAI_OUTPUT_TOKEN_LENGTH or os.environ.get("OPENAI_OUTPUT_TOKEN_LENGTH")
OPENAI_MODEL_NAME = BASE_OPENAI_MODEL_NAME or os.environ.get("OPENAI_MODEL_NAME")
# 向量配置
VECTOR_DATABASE_TYPE = BASE_VECTOR_DATABASE_TYPE or os.environ.get("VECTOR_DATABASE_TYPE")
VECTOR_EMBEDDINGS_MODEL = BASE_VECTOR_EMBEDDINGS_MODEL or os.environ.get("VECTOR_EMBEDDINGS_MODEL")
VECTOR_EMBEDDINGS_MODEL_TYPE = BASE_VECTOR_EMBEDDINGS_MODEL_TYPE or os.environ.get("VECTOR_EMBEDDINGS_MODEL_TYPE")

# 向量库配置
PGVECTOR_DRIVER = TEST_PGVECTOR_DRIVER if APPLICATION_ENV_IS_TEST else PROD_PGVECTOR_DRIVER
PGVECTOR_HOST = TEST_PGVECTOR_HOST if APPLICATION_ENV_IS_TEST else PROD_PGVECTOR_HOST
PGVECTOR_PORT = TEST_PGVECTOR_PORT if APPLICATION_ENV_IS_TEST else PROD_PGVECTOR_PORT
PGVECTOR_DATABASE = TEST_PGVECTOR_DATABASE if APPLICATION_ENV_IS_TEST else PROD_PGVECTOR_DATABASE
PGVECTOR_USER = TEST_PGVECTOR_USER if APPLICATION_ENV_IS_TEST else PROD_PGVECTOR_USER
PGVECTOR_PASSWORD = TEST_PGVECTOR_PASSWORD if APPLICATION_ENV_IS_TEST else PROD_PGVECTOR_PASSWORD
PGVECTOR_DIMENSIONS = TEST_PGVECTOR_DIMENSIONS if APPLICATION_ENV_IS_TEST else PROD_PGVECTOR_DIMENSIONS
# 业务库配置
MYSQL_HOST = TEST_MYSQL_HOST if APPLICATION_ENV_IS_TEST else PROD_MYSQL_HOST
MYSQL_PORT = TEST_MYSQL_PORT if APPLICATION_ENV_IS_TEST else PROD_MYSQL_PORT
MYSQL_CHARSET = TEST_MYSQL_CHARSET if APPLICATION_ENV_IS_TEST else PROD_MYSQL_CHARSET
MYSQL_DATABASE = TEST_MYSQL_DATABASE if APPLICATION_ENV_IS_TEST else PROD_MYSQL_DATABASE
MYSQL_USER = TEST_MYSQL_USER if APPLICATION_ENV_IS_TEST else PROD_MYSQL_USER
MYSQL_PASSWD = TEST_MYSQL_PASSWD if APPLICATION_ENV_IS_TEST else PROD_MYSQL_PASSWD
# 缓存库配置
REDIS_HOST = TEST_REDIS_HOST if APPLICATION_ENV_IS_TEST else PROD_REDIS_HOST
REDIS_PORT = TEST_REDIS_PORT if APPLICATION_ENV_IS_TEST else PROD_REDIS_PORT
REDIS_DATABASE = TEST_REDIS_DATABASE if APPLICATION_ENV_IS_TEST else PROD_REDIS_DATABASE
REDIS_PASSWD = TEST_REDIS_PASSWD if APPLICATION_ENV_IS_TEST else PROD_REDIS_PASSWD
REDIS_MIN = TEST_REDIS_MIN if APPLICATION_ENV_IS_TEST else PROD_REDIS_MIN
REDIS_MAX = TEST_REDIS_MAX if APPLICATION_ENV_IS_TEST else PROD_REDIS_MAX

# 上传文件临时目录
CONTENT_PATH = os.environ.get("CONTENT_PATH") or 'E:\\Resource\\vector\\'
# Chunk块默认长度
SPLIT_LENGTH_FUNCTION = None
# Chunk块默认大小
SPLIT_CHUNK_SIZE = 800
SPLIT_SENTENCE_SIZE = 100
# Chunk类型
SPLIT_CHUNK_TYPE = "stuff"
# Chunk块默认重叠值
SPLIT_CHUNK_OVERLAP = 100
SPLIT_SENTENCE_OVERLAP = 0
# 常规默认匹配最近N条矢量数据
VECTOR_SEARCH_TOP_K = 2
# 语义搜索阈值
VECTOR_SEARCH_SCORE = 0.6
# 长程记忆配置信息
MEMORY_LIMIT_SIZE = 2
# 文件向量化定时任务间隔频率,单位秒
SCHEDULES_ENABLED = True
if os.environ.get("SCHEDULES_ENABLED") == 'False':
    SCHEDULES_ENABLED = False
SCHEDULES_RATE_SECOND = 10
SCHEDULES_FILE_RETRY_COUNT = 3
SCHEDULES_FILE_LIMIT_COUNT = 5
# 敏感词更新定时任务，单位秒
SCHEDULES_PROHIBITED = True
SCHEDULES_PROHIBITED_SECONDS = 86400
# 免责声明更新定时任务，单位秒
SCHEDULES_DISCLAIMER = True
SCHEDULES_DISCLAIMER_SECONDS = 86400
# 网站信息抓取更新定时任务，单位秒
SCHEDULES_SPIDER = True
SCHEDULES_SPIDER_SECONDS = 3600
# 爬虫文件保存路径
SPIDER_FILE_PATH = "/data/knowledge-chatommi/namespace/{namespace_id}/{today_date}/{file_name}"
# 分片的图标识别前后缀
CHUNK_IMAGE_PREFIX = ""
CHUNK_IMAGE_SUFFIX = ""
CHUNK_IMAGE_LABELS = "[{name}](/content/{path} '')"
CHUNK_IMAGE_NAS_LABELS = "[{name}]({path} '')"
# 按句子分割策略分隔符
SEPARATORS_SENTENCE = ['。', '.', '?']
# 溯源文件后缀清单
TRACE_SUFFIX_LIST = [".docx", ".DOCX", ".pdf", ".PDF"]
# 标品默认免责声明
DEFAULT_HAVE_TRACE = '以上是参考了【{trace_content}】结合人工智能技术所提供的内容，可能存在一定的局限性。建议您在使用时谨慎判断，咨询相关领域的专业人士或参考更多来源的信息进行验证。'
DEFAULT_NOT_TRACE = '以上是由人工智能技术所提供的内容，仅作为参考，并不能替代专业的意见或建议。在做出任何决策之前，建议您综合考虑多方信息，并咨询相关领域的专业人士。'
# 分片策略声明
CHUNK_STRATEGY_SMART = '111'
CHUNK_STRATEGY_TEXT_LENGTH = '211'
CHUNK_STRATEGY_TEXT_SENTENCE = '212'
CHUNK_STRATEGY_TEXT_SENTENCE_BY_WINDOW = '212_1'
CHUNK_STRATEGY_TEXT_SEMANTICS = '213'
CHUNK_STRATEGY_TEXT_QA = '214'
CHUNK_STRATEGY_TEXT_EXCEL = '215'
CHUNK_STRATEGY_TEXT_PICTURE = '216'
CHUNK_STRATEGY_TEXT_NO_CHUNK = '217'
# 每次轮询需更新爬虫网站信息数据条数
PAGE_SIZE = 100
# 机器人角色默认信息
DEFAULT_CHAT_BOT_ROLE = "You are a helpful assistant"
TAVILY_API_KEY = "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"
HTTP_HOST = TEST_HTTP_HOST if APPLICATION_ENV_IS_TEST else PROD_HTTP_HOST
# 意图识别模型
INTENTION_RECOGNITION_MODEL = TEST_INTENTION_RECOGNITION_MODEL if APPLICATION_ENV_IS_TEST else PROD_INTENTION_RECOGNITION_MODEL
INTENTION_RECOGNITION_MODEL_NAME = TEST_INTENTION_RECOGNITION_MODEL_NAME if APPLICATION_ENV_IS_TEST else PROD_INTENTION_RECOGNITION_MODEL_NAME
# 问题优化模型
QUES_OPTIMIZER_MODEL = TEST_QUES_OPTIMIZER_MODEL if APPLICATION_ENV_IS_TEST else PROD_QUES_OPTIMIZER_MODEL
QUES_OPTIMIZER_MODEL_NAME = TEST_QUES_OPTIMIZER_MODEL_NAME if APPLICATION_ENV_IS_TEST else PROD_QUES_OPTIMIZER_MODEL_NAME
# 文件summary模型
FILES_SUMMARY_MODEL = TEST_FILES_SUMMARY_MODEL if APPLICATION_ENV_IS_TEST else PROD_FILES_SUMMARY_MODEL
FILES_SUMMARY_MODEL_NAME = TEST_FILES_SUMMARY_MODEL_NAME if APPLICATION_ENV_IS_TEST else PROD_FILES_SUMMARY_MODEL_NAME
# 深度思考模型
THINKING_MODEL = TEST_THINKING_MODEL if APPLICATION_ENV_IS_TEST else PROD_THINKING_MODEL
THINKING_MODEL_NAME = TEST_THINKING_MODEL_NAME if APPLICATION_ENV_IS_TEST else PROD_THINKING_MODEL_NAME

# AES密钥和偏移量
AES_IV = "aGFsZW9uMjAyNDA0MDAwMA=="  # 偏移量
AES_KEY = "aGFsZW9uMjAyNDA0MDAwMGhhbGVvbjIwMjQwNDAwMDA="  # 密钥
